<?php

declare(strict_types=1);

namespace App\Services;

use App\Enums\RunescapeQuestStatus;
use App\Enums\RunescapeQuestTypes;
use App\Enums\RunescapeTypes;

class QuestService implements OsrsService
{
    public function translate(array &$data): void
    {
        $quests = $this->getValuesToTrack();

        foreach ($quests as $questName => $quest) {
            $item = &$data[$questName];

            if (!$item) {
                $data[$quest['questType']->value][$questName] = RunescapeQuestStatus::Unknown;
            } else {
                if (!$item['value'] || $item['value'] <= $quest['startValue']) {
                    $data[$quest['questType']->value][$questName] = RunescapeQuestStatus::NotStarted;
                } elseif ($item['value'] >= $quest['endValue']) {
                    $data[$quest['questType']->value][$questName] = RunescapeQuestStatus::Complete;
                } else {
                    $data[$quest['questType']->value][$questName] = RunescapeQuestStatus::InProgress;
                }
            }

            unset($item);
        }
    }

    public function getValuesToTrack(): array
    {
        $data = [
            $this->makeObject(
                'A Kingdom Divided',
                12296,
                RunescapeTypes::VarBit,
                0,
                150,
            ),
            $this->makeObject(
                'A Night at the Theatre',
                12276,
                RunescapeTypes::VarBit,
                0,
                86,
            ),
            $this->makeObject(
                'A Porcine of Interest',
                10582,
                RunescapeTypes::VarBit,
                0,
                40,
            ),
            $this->makeObject(
                "A Soul's Bane",
                2011,
                RunescapeTypes::VarBit,
                0,
                13,
            ),
            $this->makeObject(
                'A Tail of Two Cats',
                1028,
                RunescapeTypes::VarBit,
                0,
                70,
            ),
            $this->makeObject(
                'A Taste of Hope',
                6396,
                RunescapeTypes::VarBit,
                0,
                165,
            ),
            $this->makeObject(
                'Alfred Grimhand\'s Barcrawl',
                13714,
                RunescapeTypes::VarBit,
                0,
                2,
                RunescapeQuestTypes::Miniquest
            ),
            $this->makeObject(
                'Animal Magnetism',
                3185,
                RunescapeTypes::VarBit,
                0,
                240,
            ),
            $this->makeObject(
                'Another Slice of Ham',
                3550,
                RunescapeTypes::VarBit,
                0,
                11,
            ),
            $this->makeObject(
                'Architectural Alliance',
                13784,
                RunescapeTypes::VarBit,
                0,
                3,
                RunescapeQuestTypes::Miniquest,
            ),
            $this->makeObject(
                'Bear Your Soul',
                5078,
                RunescapeTypes::VarBit,
                0,
                3,
                RunescapeQuestTypes::Miniquest,
            ),
            $this->makeObject(
                'Below Ice Mountain',
                12063,
                RunescapeTypes::VarBit,
                0,
                120,
            ),
            $this->makeObject(
                'Beneath Cursed Sands',
                13841,
                RunescapeTypes::VarBit,
                0,
                108,
            ),
            $this->makeObject(
                'Between a Rock',
                299,
                RunescapeTypes::VarBit,
                0,
                110,
            ),
            $this->makeObject(
                'Bone Voyage',
                5795,
                RunescapeTypes::VarBit,
                0,
                50,
            ),
            $this->makeObject(
                'Client of Kourend',
                5619,
                RunescapeTypes::VarBit,
                0,
                7,
            ),
            $this->makeObject(
                'Cold War',
                3293,
                RunescapeTypes::VarBit,
                0,
                135,
            ),
            $this->makeObject(
                'Contact!',
                3274,
                RunescapeTypes::VarBit,
                0,
                130,
            ),
            $this->makeObject(
                'Creature of Fenkenstrain',
                13715,
                RunescapeTypes::VarBit,
                0,
                9
            ),
            $this->makeObject(
                'Curse of the Empty Lord',
                13713,
                RunescapeTypes::VarBit,
                0,
                6,
                RunescapeQuestTypes::Miniquest
            ),
            $this->makeObject(
                "Daddy's Home",
                10570,
                RunescapeTypes::VarBit,
                0,
                13,
                RunescapeQuestTypes::Miniquest,
            ),
            $this->makeObject(
                'Darkness of Hallowvale',
                2573,
                RunescapeTypes::VarBit,
                0,
                320,
            ),
            $this->makeObject(
                'Death to the Dorgeshuun',
                2258,
                RunescapeTypes::VarBit,
                0,
                13,
            ),
            $this->makeObject(
                'Demon Slayer',
                2561,
                RunescapeTypes::VarBit,
                0,
                3,
            ),
            $this->makeObject(
                'Desert Treasure I',
                358,
                RunescapeTypes::VarBit,
                0,
                15,
            ),
            $this->makeObject(
                'Desert Treasure II - The Fallen Empire',
                14862,
                RunescapeTypes::VarBit,
                0,
                118,
            ),
            $this->makeObject(
                'Devious Minds',
                1465,
                RunescapeTypes::VarBit,
                0,
                80,
            ),
            $this->makeObject(
                'Dragon Slayer II',
                6104,
                RunescapeTypes::VarBit,
                0,
                215,
            ),
            $this->makeObject(
                'Dream Mentor',
                3618,
                RunescapeTypes::VarBit,
                0,
                28,
            ),
            $this->makeObject(
                "Eagle's Peak",
                2780,
                RunescapeTypes::VarBit,
                0,
                40,
            ),
            $this->makeObject(
                'Elemental Workshop I',
                13718,
                RunescapeTypes::VarBit,
                0,
                2,
            ),
            $this->makeObject(
                'Elemental Workshop II',
                2639,
                RunescapeTypes::VarBit,
                0,
                11,
            ),
            $this->makeObject(
                "Enakhra's Lament",
                1560,
                RunescapeTypes::VarBit,
                0,
                70,
            ),
            $this->makeObject(
                'Enlightened Journey',
                2866,
                RunescapeTypes::VarBit,
                0,
                200,
            ),
            $this->makeObject(
                'Fairytale I - Growing Pains',
                1803,
                RunescapeTypes::VarBit,
                0,
                90,
            ),
            $this->makeObject(
                'Fairytale II - Cure a Queen',
                2326,
                RunescapeTypes::VarBit,
                10,
                90
            ),
            $this->makeObject(
                'Family Pest',
                5347,
                RunescapeTypes::VarBit,
                0,
                3,
                RunescapeQuestTypes::Miniquest,
            ),
            $this->makeObject(
                'Forgettable Tale',
                822,
                RunescapeTypes::VarBit,
                0,
                140,
            ),
            $this->makeObject(
                'Garden of Tranquillity',
                961,
                RunescapeTypes::VarBit,
                0,
                60,
            ),
            $this->makeObject(
                'Getting Ahead',
                693,
                RunescapeTypes::VarBit,
                0,
                34,
            ),
            $this->makeObject(
                "Ghost's ahoy",
                217,
                RunescapeTypes::VarBit,
                0,
                8,
            ),
            $this->makeObject(
                'Goblin Diplomacy',
                2378,
                RunescapeTypes::VarBit,
                0,
                6,
            ),
            $this->makeObject(
                'Grim Tales',
                2783,
                RunescapeTypes::VarBit,
                0,
                60,
            ),
            $this->makeObject(
                "Hopespear's Will",
                13619,
                RunescapeTypes::VarBit,
                0,
                2,
                RunescapeQuestTypes::Miniquest
            ),
            $this->makeObject(
                'Horror from the Deep',
                34,
                RunescapeTypes::VarBit,
                0,
                10,
            ),
            $this->makeObject(
                "Icthlarin's Little Helper",
                418,
                RunescapeTypes::VarBit,
                0,
                26,
            ),
            $this->makeObject(
                'In Aid of the Myreque',
                1990,
                RunescapeTypes::VarBit,
                0,
                430,
            ),
            $this->makeObject(
                'In Search of Knowledge',
                8403,
                RunescapeTypes::VarBit,
                0,
                3,
                RunescapeQuestTypes::Miniquest,
            ),
            $this->makeObject(
                'Into the Tombs',
                13836,
                RunescapeTypes::VarBit,
                0,
                24,
                RunescapeQuestTypes::Miniquest,
            ),
            $this->makeObject(
                "King's ransom",
                3888,
                RunescapeTypes::VarBit,
                0,
                90,
            ),
            $this->makeObject(
                'Lair of Tarn Razorlor',
                3290,
                RunescapeTypes::VarBit,
                0,
                3,
                RunescapeQuestTypes::Miniquest,
            ),
            $this->makeObject(
                'Land of the Goblins',
                13599,
                RunescapeTypes::VarBit,
                0,
                56,
            ),
            $this->makeObject(
                'Lunar Diplomacy',
                2448,
                RunescapeTypes::VarBit,
                0,
                190,
            ),
            $this->makeObject(
                'Mage Arena II',
                6067,
                RunescapeTypes::VarBit,
                0,
                4,
                RunescapeQuestTypes::Miniquest,
            ),
            $this->makeObject(
                'Making Friends with my Arm',
                6528,
                RunescapeTypes::VarBit,
                0,
                200,
            ),
            $this->makeObject(
                'Making History',
                1383,
                RunescapeTypes::VarBit,
                0,
                4,
            ),
            $this->makeObject(
                'Misthalin Mystery',
                1383,
                RunescapeTypes::VarBit,
                0,
                4,
            ),
            $this->makeObject(
                'Monkey Madness II',
                5027,
                RunescapeTypes::VarBit,
                0,
                195,
            ),
            $this->makeObject(
                'Mountain Daughter',
                260,
                RunescapeTypes::VarBit,
                0,
                70,
            ),
            $this->makeObject(
                "Mourning's End Part 2",
                1103,
                RunescapeTypes::VarBit,
                0,
                60,
            ),
            $this->makeObject(
                'My Arms Big Adventure',
                2790,
                RunescapeTypes::VarBit,
                0,
                320,
            ),
            $this->makeObject(
                "Olaf's quest",
                3534,
                RunescapeTypes::VarBit,
                0,
                80,
            ),
            $this->makeObject(
                'Ratcatchers',
                144,
                RunescapeTypes::VarBit,
                0,
                127,
            ),
            $this->makeObject(
                'Recipe for Disaster',
                1850,
                RunescapeTypes::VarBit,
                0,
                5,
            ),
            $this->makeObject(
                'Recruitment Drive',
                657,
                RunescapeTypes::VarBit,
                0,
                2,
            ),
            $this->makeObject(
                'Royal Trouble',
                2140,
                RunescapeTypes::VarBit,
                0,
                30,
            ),
            $this->makeObject(
                'Secrets of the North',
                14722,
                RunescapeTypes::VarBit,
                0,
                90,
            ),
            $this->makeObject(
                'Shadow of the Storm',
                1372,
                RunescapeTypes::VarBit,
                0,
                125,
            ),
            $this->makeObject(
                'Shield of Arrav',
                13716,
                RunescapeTypes::VarBit,
                0,
                2,
            ),
            $this->makeObject(
                'Sins of the Father',
                7255,
                RunescapeTypes::VarBit,
                0,
                138,
            ),
            $this->makeObject(
                'Skippy and the Mogres',
                1344,
                RunescapeTypes::VarBit,
                0,
                3,
                RunescapeQuestTypes::Miniquest,
            ),
            $this->makeObject(
                'Sleeping Giants',
                13902,
                RunescapeTypes::VarBit,
                0,
                30,
            ),
            $this->makeObject(
                'Song of the Elves',
                9016,
                RunescapeTypes::VarBit,
                0,
                200,
            ),
            $this->makeObject(
                'Spirits of the Ellid',
                1444,
                RunescapeTypes::VarBit,
                0,
                60,
            ),
            $this->makeObject(
                'Swam Song',
                2098,
                RunescapeTypes::VarBit,
                0,
                200,
            ),
            $this->makeObject(
                'Tale of the Righteous',
                6358,
                RunescapeTypes::VarBit,
                0,
                17,
            ),
            $this->makeObject(
                'Tears of Guthix',
                451,
                RunescapeTypes::VarBit,
                0,
                2,
            ),
            $this->makeObject(
                'Temple of the Eye',
                13738,
                RunescapeTypes::VarBit,
                0,
                130,
            ),
            $this->makeObject(
                'The Ascent of Aceuus',
                7856,
                RunescapeTypes::VarBit,
                0,
                14,
            ),
            $this->makeObject(
                'The Corsair Curse',
                6071,
                RunescapeTypes::VarBit,
                0,
                60,
            ),
            $this->makeObject(
                'The Depths of Despair',
                6027,
                RunescapeTypes::VarBit,
                0,
                11,
            ),
            $this->makeObject(
                'The Enchanted Key',
                13717,
                RunescapeTypes::VarBit,
                0,
                2,
                RunescapeQuestTypes::Miniquest,
            ),
            $this->makeObject(
                'The Eyes of Glouphrie',
                2497,
                RunescapeTypes::VarBit,
                0,
                60,
            ),
            $this->makeObject(
                'The Feud',
                334,
                RunescapeTypes::VarBit,
                0,
                28,
            ),
            $this->makeObject(
                'The Forsaken Tower',
                7796,
                RunescapeTypes::VarBit,
                0,
                11,
            ),
            $this->makeObject(
                'The Fremennik Exiles',
                9459,
                RunescapeTypes::VarBit,
                0,
                130,
            ),
            $this->makeObject(
                'The Freminnik Isles',
                3311,
                RunescapeTypes::VarBit,
                0,
                340,
            ),
            $this->makeObject(
                'The Frozen Door',
                13175,
                RunescapeTypes::VarBit,
                0,
                10,
                RunescapeQuestTypes::Miniquest
            ),
            $this->makeObject(
                'The Garden of Death',
                14609,
                RunescapeTypes::VarBit,
                0,
                56,
            ),
            $this->makeObject(
                "The General's Shadow",
                3330,
                RunescapeTypes::VarBit,
                0,
                30,
                RunescapeQuestTypes::Miniquest,
            ),
            $this->makeObject(
                'The Giant Dwarf',
                571,
                RunescapeTypes::VarBit,
                0,
                50,
            ),
            $this->makeObject(
                'The Golem',
                346,
                RunescapeTypes::VarBit,
                0,
                10,
            ),
            $this->makeObject(
                'The Hand in the Sand',
                1527,
                RunescapeTypes::VarBit,
                0,
                160,
            ),
            $this->makeObject(
                'The Lost Tribe',
                532,
                RunescapeTypes::VarBit,
                0,
                11,
            ),
            $this->makeObject(
                'The Queen of Thieves',
                6037,
                RunescapeTypes::VarBit,
                0,
                13,
            ),
            $this->makeObject(
                'The Slug Menace',
                2610,
                RunescapeTypes::VarBit,
                0,
                14,
            ),
            $this->makeObject(
                'Tower of Life',
                3337,
                RunescapeTypes::VarBit,
                0,
                18,
            ),
            $this->makeObject(
                'Wanted',
                1051,
                RunescapeTypes::VarBit,
                0,
                11,
            ),
            $this->makeObject(
                'What Lies Below',
                3523,
                RunescapeTypes::VarBit,
                0,
                150,
            ),
            $this->makeObject(
                'X Marks the Spot',
                8063,
                RunescapeTypes::VarBit,
                0,
                8,
            ),
            $this->makeObject(
                'Zogre Flesh Eaters',
                487,
                RunescapeTypes::VarBit,
                0,
                11,
            ),
            $this->makeObject(
                'Big Chompy Bird Hunting',
                293,
                RunescapeTypes::VarPlayer,
                0,
                65,
            ),
            $this->makeObject(
                'Biohazard',
                68,
                RunescapeTypes::VarPlayer,
                0,
                16,
            ),
            $this->makeObject(
                "Black Knights' Fortress",
                130,
                RunescapeTypes::VarPlayer,
                0,
                4,
            ),
            $this->makeObject(
                'Cabin Fever',
                655,
                RunescapeTypes::VarPlayer,
                0,
                140
            ),
            $this->makeObject(
                'Clock Tower',
                10,
                RunescapeTypes::VarPlayer,
                0,
                8,
            ),
            $this->makeObject(
                "Cook's assistant",
                29,
                RunescapeTypes::VarPlayer,
                0,
                2,
            ),
            $this->makeObject(
                'Death Plateau',
                314,
                RunescapeTypes::VarPlayer,
                0,
                80,
            ),
            $this->makeObject(
                "Doric's Quest",
                31,
                RunescapeTypes::VarPlayer,
                0,
                100,
            ),
            $this->makeObject(
                'Dragon Slayer I',
                176,
                RunescapeTypes::VarPlayer,
                0,
                10,
            ),
            $this->makeObject(
                'Druidic Ritual',
                80,
                RunescapeTypes::VarPlayer,
                0,
                4,
            ),
            $this->makeObject(
                'Dwarf Cannon',
                0,
                RunescapeTypes::VarPlayer,
                0,
                11,
            ),
            $this->makeObject(
                "Eadgar's Ruse",
                335,
                RunescapeTypes::VarPlayer,
                0,
                110,
            ),
            $this->makeObject(
                'Enter the Abyss',
                492,
                RunescapeTypes::VarPlayer,
                0,
                4,
                RunescapeQuestTypes::Miniquest,
            ),
            $this->makeObject(
                'Ernest the Chicken',
                148,
                RunescapeTypes::VarPlayer,
                0,
                11,
            ),
            $this->makeObject(
                'Family Crest',
                148,
                RunescapeTypes::VarPlayer,
                0,
                11,
            ),
            $this->makeObject(
                'Fight Arena',
                17,
                RunescapeTypes::VarPlayer,
                0,
                14,
            ),
            $this->makeObject(
                'Fishing Contest',
                11,
                RunescapeTypes::VarPlayer,
                0,
                5,
            ),
            $this->makeObject(
                "Gertrude's cat",
                180,
                RunescapeTypes::VarPlayer,
                0,
                6,
            ),
            $this->makeObject(
                'Haunted Mine',
                382,
                RunescapeTypes::VarPlayer,
                0,
                11,
            ),
            $this->makeObject(
                'Hazeel Cult',
                223,
                RunescapeTypes::VarPlayer,
                0,
                9,
            ),
            $this->makeObject(
                "Heroes' Quest",
                188,
                RunescapeTypes::VarPlayer,
                0,
                15,
            ),
            $this->makeObject(
                'Holy Grail',
                5,
                RunescapeTypes::VarPlayer,
                0,
                10,
            ),
            $this->makeObject(
                'Imp Catcher',
                160,
                RunescapeTypes::VarPlayer,
                0,
                2,
            ),
            $this->makeObject(
                'In Search of the Myreque',
                387,
                RunescapeTypes::VarPlayer,
                0,
                105,
            ),
            $this->makeObject(
                'Jungle Potion',
                175,
                RunescapeTypes::VarPlayer,
                0,
                12,
            ),
            $this->makeObject(
                "Legends' Quest",
                139,
                RunescapeTypes::VarPlayer,
                0,
                75,
            ),
            $this->makeObject(
                'Lost City',
                147,
                RunescapeTypes::VarPlayer,
                0,
                6,
            ),
            $this->makeObject(
                'Mage Arena I',
                267,
                RunescapeTypes::VarPlayer,
                0,
                8,
                RunescapeQuestTypes::Miniquest,
            ),
            $this->makeObject(
                "Merlin's Crystal",
                14,
                RunescapeTypes::VarPlayer,
                0,
                7,
            ),
            $this->makeObject(
                "Monk's Friend",
                30,
                RunescapeTypes::VarPlayer,
                0,
                80,
            ),
            $this->makeObject(
                'Monkey Madness I',
                365,
                RunescapeTypes::VarPlayer,
                0,
                9,
            ),
            $this->makeObject(
                "Mourning's End Part I",
                517,
                RunescapeTypes::VarPlayer,
                0,
                9,
            ),
            $this->makeObject(
                'Murder Mystery',
                192,
                RunescapeTypes::VarPlayer,
                0,
                2,
            ),
            $this->makeObject(
                'Nature Spirit',
                307,
                RunescapeTypes::VarPlayer,
                0,
                110,
            ),
            $this->makeObject(
                'Observatory Quest',
                112,
                RunescapeTypes::VarPlayer,
                0,
                7,
            ),
            $this->makeObject(
                'One Small Favour',
                416,
                RunescapeTypes::VarPlayer,
                0,
                285,
            ),
            $this->makeObject(
                "Pirate's Treasure",
                71,
                RunescapeTypes::VarPlayer,
                0,
                4,
            ),
            $this->makeObject(
                'Plague City',
                165,
                RunescapeTypes::VarPlayer,
                0,
                29,
            ),
            $this->makeObject(
                'Priest in Peril',
                302,
                RunescapeTypes::VarPlayer,
                0,
                60,
            ),
            $this->makeObject(
                'Prince Ali Rescue',
                273,
                RunescapeTypes::VarPlayer,
                0,
                110,
            ),
            $this->makeObject(
                'Rag and Bone Man I',
                714,
                RunescapeTypes::VarPlayer,
                0,
                4,
            ),
            $this->makeObject(
                "Rag and Bone Man II",
                714,
                RunescapeTypes::VarPlayer,
                3,
                6,
            ),
            $this->makeObject(
                'Regicide',
                328,
                RunescapeTypes::VarPlayer,
                0,
                15,
            ),
            $this->makeObject(
                'Romeo and Juliet',
                144,
                RunescapeTypes::VarPlayer,
                0,
                100,
            ),
            $this->makeObject(
                'Roving Elves',
                402,
                RunescapeTypes::VarPlayer,
                0,
                6,
            ),
            $this->makeObject(
                'Rum Deal',
                600,
                RunescapeTypes::VarPlayer,
                0,
                19,
            ),
            $this->makeObject(
                'Rune Mysteries',
                63,
                RunescapeTypes::VarPlayer,
                0,
                6,
            ),
            $this->makeObject(
                'Scorpion Catcher',
                76,
                RunescapeTypes::VarPlayer,
                0,
                6,
            ),
            $this->makeObject(
                'Sea Slug',
                159,
                RunescapeTypes::VarPlayer,
                0,
                12,
            ),
            $this->makeObject(
                "Shades of Mort'ton",
                339,
                RunescapeTypes::VarPlayer,
                0,
                85,
            ),
            $this->makeObject(
                'Sheep herder',
                60,
                RunescapeTypes::VarPlayer,
                0,
                3,
            ),
            $this->makeObject(
                'Shilo Village',
                116,
                RunescapeTypes::VarPlayer,
                0,
                15,
            ),
            $this->makeObject(
                'Tai Bwo Wannai Trio',
                320,
                RunescapeTypes::VarPlayer,
                2,
                6,
            ),
            $this->makeObject(
                'Temple of Ikov',
                26,
                RunescapeTypes::VarPlayer,
                0,
                80,
            ),
            $this->makeObject(
                'The Digsite',
                131,
                RunescapeTypes::VarPlayer,
                0,
                9,
            ),
            $this->makeObject(
                'The Fremennik Trials',
                347,
                RunescapeTypes::VarPlayer,
                0,
                10,
            ),
            $this->makeObject(
                'The Grand Tree',
                150,
                RunescapeTypes::VarPlayer,
                0,
                160,
            ),
            $this->makeObject(
                'The Great Brain Robbery',
                980,
                RunescapeTypes::VarPlayer,
                0,
                130,
            ),
            $this->makeObject(
                "The Knight's Sword",
                122,
                RunescapeTypes::VarPlayer,
                0,
                7,
            ),
            $this->makeObject(
                'The Restless Ghost',
                107,
                RunescapeTypes::VarPlayer,
                0,
                5,
            ),
            $this->makeObject(
                'The Tourist Trap',
                197,
                RunescapeTypes::VarPlayer,
                0,
                30,
            ),
            $this->makeObject(
                'Throne of Miscellania',
                359,
                RunescapeTypes::VarPlayer,
                0,
                100,
            ),
            $this->makeObject(
                'Tree Gnome Village',
                111,
                RunescapeTypes::VarPlayer,
                0,
                9,
            ),
            $this->makeObject(
                'Tribal Totem',
                200,
                RunescapeTypes::VarPlayer,
                0,
                5,
            ),
            $this->makeObject(
                'Troll Romance',
                385,
                RunescapeTypes::VarPlayer,
                0,
                45,
            ),
            $this->makeObject(
                'Troll Stronghold',
                317,
                RunescapeTypes::VarPlayer,
                0,
                50,
            ),
            $this->makeObject(
                'Underground Pass',
                161,
                RunescapeTypes::VarPlayer,
                0,
                11,
            ),
            $this->makeObject(
                'Vampyre Slayer',
                178,
                RunescapeTypes::VarPlayer,
                0,
                3,
            ),
            $this->makeObject(
                'Watchtower',
                212,
                RunescapeTypes::VarPlayer,
                0,
                13,
            ),
            $this->makeObject(
                'Waterfall quest',
                65,
                RunescapeTypes::VarPlayer,
                0,
                10,
            ),
            $this->makeObject(
                "Witch's house",
                226,
                RunescapeTypes::VarPlayer,
                0,
                7,
            ),
            $this->makeObject(
                "Witch's potion",
                67,
                RunescapeTypes::VarPlayer,
                0,
                3,
            ),
        ];

        usort($data, fn ($a, $b) => strcmp($a['text'], $b['text']));

        return $data;
    }

    private function makeObject(
        string $text,
        int $index,
        RunescapeTypes $type,
        int $startValue,
        int $endValue,
        RunescapeQuestTypes $questType = RunescapeQuestTypes::Quest,
    ): array {
        return [
            'index' => $index,
            'type' => $type,
            'questType' => $questType,
            'startValue' => $startValue,
            'endValue' => $endValue,
            'text' => $text
        ];
    }
}
