<?php

declare(strict_types=1);

namespace App\Services;

use App\Enums\RunescapeQuestStatus;
use App\Enums\RunescapeQuestTypes;
use App\Enums\RunescapeTypes;

class QuestService implements OsrsService
{
    public function translate(array &$data): void
    {
        $quests = $this->getValuesToTrack();

        foreach ($quests as $questName => $quest) {
            $item = &$data[$questName];

            if (!$item) {
                $data[$quest['questType']->value][$questName] = RunescapeQuestStatus::Unknown;
            } else {
                if (!$item['value'] || $item['value'] <= $quest['startValue']) {
                    $data[$quest['questType']->value][$questName] = RunescapeQuestStatus::NotStarted;
                } elseif ($item['value'] >= $quest['endValue']) {
                    $data[$quest['questType']->value][$questName] = RunescapeQuestStatus::Complete;
                } else {
                    $data[$quest['questType']->value][$questName] = RunescapeQuestStatus::InProgress;
                }
            }

            unset($item);
        }
    }

    public function getValuesToTrack(): array
    {
        $data = [
            'a_kingdom_divided' => $this->makeObject(
                'A Kingdom Divided',
                12296,
                RunescapeTypes::VarBit,
                0,
                150,
            ),
            'a_night_at_the_theatre' => $this->makeObject(
                'A Night at the Theatre',
                12276,
                RunescapeTypes::VarBit,
                0,
                86,
            ),
            'a_porcine_of_interest' => $this->makeObject(
                'A Porcine of Interest',
                10582,
                RunescapeTypes::VarBit,
                0,
                40,
            ),
            'a_souls_bane' => $this->makeObject(
                "A Soul's Bane",
                2011,
                RunescapeTypes::VarBit,
                0,
                13,
            ),
            'a_tail_of_two_cats' => $this->makeObject(
                'A Tail of Two Cats',
                1028,
                RunescapeTypes::VarBit,
                0,
                70,
            ),
            'a_taste_of_hope' => $this->makeObject(
                'A Taste of Hope',
                6396,
                RunescapeTypes::VarBit,
                0,
                165,
            ),
            'alfred_grimhand_barcrawl' => $this->makeObject(
                'Alfred Grimhand\'s Barcrawl',
                13714,
                RunescapeTypes::VarBit,
                0,
                2,
                RunescapeQuestTypes::Miniquest
            ),
            'animal_magnetism' => $this->makeObject(
                'Animal Magnetism',
                3185,
                RunescapeTypes::VarBit,
                0,
                240,
            ),
            'another_slice_of_ham' => $this->makeObject(
                'Another Slice of Ham',
                3550,
                RunescapeTypes::VarBit,
                0,
                11,
            ),
            'architectural_alliance' => $this->makeObject(
                'Architectural Alliance',
                13784,
                RunescapeTypes::VarBit,
                0,
                3,
                RunescapeQuestTypes::Miniquest,
            ),
            'bear_your_soul' => $this->makeObject(
                'Bear Your Soul',
                5078,
                RunescapeTypes::VarBit,
                0,
                3,
                RunescapeQuestTypes::Miniquest,
            ),
            'below_ice_mountain' => $this->makeObject(
                'Below Ice Mountain',
                12063,
                RunescapeTypes::VarBit,
                0,
                120,
            ),
            'beneath_cursed_sands' => $this->makeObject(
                'Beneath Cursed Sands',
                13841,
                RunescapeTypes::VarBit,
                0,
                108,
            ),
            'between_a_rock' => $this->makeObject(
                'Between a Rock',
                299,
                RunescapeTypes::VarBit,
                0,
                110,
            ),
            'bone_voyage' => $this->makeObject(
                'Bone Voyage',
                5795,
                RunescapeTypes::VarBit,
                0,
                50,
            ),
            'client_of_kourend' => $this->makeObject(
                'Client of Kourend',
                5619,
                RunescapeTypes::VarBit,
                0,
                7,
            ),
            'cold_war' => $this->makeObject(
                'Cold War',
                3293,
                RunescapeTypes::VarBit,
                0,
                135,
            ),
            'contact' => $this->makeObject(
                'Contact!',
                3274,
                RunescapeTypes::VarBit,
                0,
                130,
            ),
            'creature_of_fenkenstrain' => $this->makeObject(
                'Creature of Fenkenstrain',
                13715,
                RunescapeTypes::VarBit,
                0,
                9
            ),
            'curse_of_the_empty_lord' => $this->makeObject(
                'Curse of the Empty Lord',
                13713,
                RunescapeTypes::VarBit,
                0,
                6,
                RunescapeQuestTypes::Miniquest
            ),
            'daddys_home' => $this->makeObject(
                "Daddy's Home",
                10570,
                RunescapeTypes::VarBit,
                0,
                13,
                RunescapeQuestTypes::Miniquest,
            ),
            'darkness_of_hallowvale' => $this->makeObject(
                'Darkness of Hallowvale',
                2573,
                RunescapeTypes::VarBit,
                0,
                320,
            ),
            'death_to_the_dorgeshuun' => $this->makeObject(
                'Death to the Dorgeshuun',
                2258,
                RunescapeTypes::VarBit,
                0,
                13,
            ),
            'demon_slayer' => $this->makeObject(
                'Demon Slayer',
                2561,
                RunescapeTypes::VarBit,
                0,
                3,
            ),
            'desert_treasure_1' => $this->makeObject(
                'Desert Treasure I',
                358,
                RunescapeTypes::VarBit,
                0,
                15,
            ),
            'desert_treasure_2' => $this->makeObject(
                'Desert Treasure II - The Fallen Empire',
                14862,
                RunescapeTypes::VarBit,
                0,
                118,
            ),
            'devious_minds' => $this->makeObject(
                'Devious Minds',
                1465,
                RunescapeTypes::VarBit,
                0,
                80,
            ),
            'dragon_slayer_2' => $this->makeObject(
                'Dragon Slayer II',
                6104,
                RunescapeTypes::VarBit,
                0,
                215,
            ),
            'dream_mentor' => $this->makeObject(
                'Dream Mentor',
                3618,
                RunescapeTypes::VarBit,
                0,
                28,
            ),
            'eagles_peak' => $this->makeObject(
                "Eagle's Peak",
                2780,
                RunescapeTypes::VarBit,
                0,
                40,
            ),
            'elemental_workshop_1' => $this->makeObject(
                'Elemental Workshop I',
                13718,
                RunescapeTypes::VarBit,
                0,
                2,
            ),
            'elemental_workshop_2' => $this->makeObject(
                'Elemental Workshop II',
                2639,
                RunescapeTypes::VarBit,
                0,
                11,
            ),
            'enakhras_lament' => $this->makeObject(
                "Enakhra's Lament",
                1560,
                RunescapeTypes::VarBit,
                0,
                70,
            ),
            'enlightened_journey' => $this->makeObject(
                'Enlightened Journey',
                2866,
                RunescapeTypes::VarBit,
                0,
                200,
            ),
            'fairytale_1_growing_pains' => $this->makeObject(
                'Fairytale I - Growing Pains',
                1803,
                RunescapeTypes::VarBit,
                0,
                90,
            ),
            'fairytale_2_cure_a_queen' => $this->makeObject(
                'Fairytale II - Cure a Queen',
                2326,
                RunescapeTypes::VarBit,
                10,
                90
            ),
            'family_pest' => $this->makeObject(
                'Family Pest',
                5347,
                RunescapeTypes::VarBit,
                0,
                3,
                RunescapeQuestTypes::Miniquest,
            ),
            'forgettable_tale' => $this->makeObject(
                'Forgettable Tale',
                822,
                RunescapeTypes::VarBit,
                0,
                140,
            ),
            'gardenn_of_tranquillity' => $this->makeObject(
                'Garden of Tranquillity',
                961,
                RunescapeTypes::VarBit,
                0,
                60,
            ),
            'getting_ahead' => $this->makeObject(
                'Getting Ahead',
                693,
                RunescapeTypes::VarBit,
                0,
                34,
            ),
            'ghosts_ahoy' => $this->makeObject(
                "Ghost's ahoy",
                217,
                RunescapeTypes::VarBit,
                0,
                8,
            ),
            'goblin_diplomacy' => $this->makeObject(
                'Goblin Diplomacy',
                2378,
                RunescapeTypes::VarBit,
                0,
                6,
            ),
            'grim_tales' => $this->makeObject(
                'Grim Tales',
                2783,
                RunescapeTypes::VarBit,
                0,
                60,
            ),
            'hopespears_will' => $this->makeObject(
                "Hopespear's Will",
                13619,
                RunescapeTypes::VarBit,
                0,
                2,
                RunescapeQuestTypes::Miniquest
            ),
            'horror_from_the_deep' => $this->makeObject(
                'Horror from the Deep',
                34,
                RunescapeTypes::VarBit,
                0,
                10,
            ),
            'icthlarins_little_helper' => $this->makeObject(
                "Icthlarin's Little Helper",
                418,
                RunescapeTypes::VarBit,
                0,
                26,
            ),
            'in_aid_of_the_myreque' => $this->makeObject(
                'In Aid of the Myreque',
                1990,
                RunescapeTypes::VarBit,
                0,
                430,
            ),
            'in_search_of_knowledge' => $this->makeObject(
                'In Search of Knowledge',
                8403,
                RunescapeTypes::VarBit,
                0,
                3,
                RunescapeQuestTypes::Miniquest,
            ),
            'into_the_tombs' => $this->makeObject(
                'Into the Tombs',
                13836,
                RunescapeTypes::VarBit,
                0,
                24,
                RunescapeQuestTypes::Miniquest,
            ),
            'kings_ransom' => $this->makeObject(
                "King's ransom",
                3888,
                RunescapeTypes::VarBit,
                0,
                90,
            ),
            'lair_of_tarn_razorlor' => $this->makeObject(
                'Lair of Tarn Razorlor',
                3290,
                RunescapeTypes::VarBit,
                0,
                3,
                RunescapeQuestTypes::Miniquest,
            ),
            'land_of_the_goblins' => $this->makeObject(
                'Land of the Goblins',
                13599,
                RunescapeTypes::VarBit,
                0,
                56,
            ),
            'lunar_diplomacy' => $this->makeObject(
                'Lunar Diplomacy',
                2448,
                RunescapeTypes::VarBit,
                0,
                190,
            ),
            'mage_arena_2' => $this->makeObject(
                'Mage Arena II',
                6067,
                RunescapeTypes::VarBit,
                0,
                4,
                RunescapeQuestTypes::Miniquest,
            ),
            'making_friends_with_my_arm' => $this->makeObject(
                'Making Friends with my Arm',
                6528,
                RunescapeTypes::VarBit,
                0,
                200,
            ),
            'making_history' => $this->makeObject(
                'Making History',
                1383,
                RunescapeTypes::VarBit,
                0,
                4,
            ),
            'misthalin_mystery' => $this->makeObject(
                'Misthalin Mystery',
                1383,
                RunescapeTypes::VarBit,
                0,
                4,
            ),
            'monkey_madness_2' => $this->makeObject(
                'Monkey Madness II',
                5027,
                RunescapeTypes::VarBit,
                0,
                195,
            ),
            'mountain_daughter' => $this->makeObject(
                'Mountain Daughter',
                260,
                RunescapeTypes::VarBit,
                0,
                70,
            ),
            'mournings_end_part_2' => $this->makeObject(
                "Mourning's End Part 2",
                1103,
                RunescapeTypes::VarBit,
                0,
                60,
            ),
            'my_arms_big_adventure' => $this->makeObject(
                'My Arms Big Adventure',
                2790,
                RunescapeTypes::VarBit,
                0,
                320,
            ),
            'olafs_quest' => $this->makeObject(
                "Olaf's quest",
                3534,
                RunescapeTypes::VarBit,
                0,
                80,
            ),
            'ratcatchers' => $this->makeObject(
                'Ratcatchers',
                144,
                RunescapeTypes::VarBit,
                0,
                127,
            ),
            'recipe_for_disaster' => $this->makeObject(
                'Recipe for Disaster',
                1850,
                RunescapeTypes::VarBit,
                0,
                5,
            ),
            'recruitment_drive' => $this->makeObject(
                'Recruitment Drive',
                657,
                RunescapeTypes::VarBit,
                0,
                2,
            ),
            'royal_trouble' => $this->makeObject(
                'Royal Trouble',
                2140,
                RunescapeTypes::VarBit,
                0,
                30,
            ),
            'secrets_of_the_north' => $this->makeObject(
                'Secrets of the North',
                14722,
                RunescapeTypes::VarBit,
                0,
                90,
            ),
            'shadow_of_the_storm' => $this->makeObject(
                'Shadow of the Storm',
                1372,
                RunescapeTypes::VarBit,
                0,
                125,
            ),
            'shield_of_arrav' => $this->makeObject(
                'Shield of Arrav',
                13716,
                RunescapeTypes::VarBit,
                0,
                2,
            ),
            'sins_of_the_father' => $this->makeObject(
                'Sins of the Father',
                7255,
                RunescapeTypes::VarBit,
                0,
                138,
            ),
            'skippy_and_the_mogres' => $this->makeObject(
                'Skippy and the Mogres',
                1344,
                RunescapeTypes::VarBit,
                0,
                3,
                RunescapeQuestTypes::Miniquest,
            ),
            'sleeping_giants' => $this->makeObject(
                'Sleeping Giants',
                13902,
                RunescapeTypes::VarBit,
                0,
                30,
            ),
            'song_of_the_elves' => $this->makeObject(
                'Song of the Elves',
                9016,
                RunescapeTypes::VarBit,
                0,
                200,
            ),
            'spirits_of_the_ellid' => $this->makeObject(
                'Spirits of the Ellid',
                1444,
                RunescapeTypes::VarBit,
                0,
                60,
            ),
            'swam_song' => $this->makeObject(
                'Swam Song',
                2098,
                RunescapeTypes::VarBit,
                0,
                200,
            ),
            'tale_of_the_righteous' => $this->makeObject(
                'Tale of the Righteous',
                6358,
                RunescapeTypes::VarBit,
                0,
                17,
            ),
            'tears_of_guthix' => $this->makeObject(
                'Tears of Guthix',
                451,
                RunescapeTypes::VarBit,
                0,
                2,
            ),
            'temple_of_the_eye' => $this->makeObject(
                'Temple of the Eye',
                13738,
                RunescapeTypes::VarBit,
                0,
                130,
            ),
            'the_ascent_of_aceuus' => $this->makeObject(
                'The Ascent of Aceuus',
                7856,
                RunescapeTypes::VarBit,
                0,
                14,
            ),
            'the_corsair_curse' => $this->makeObject(
                'The Corsair Curse',
                6071,
                RunescapeTypes::VarBit,
                0,
                60,
            ),
            'the_depths_of_despair' => $this->makeObject(
                'The Depths of Despair',
                6027,
                RunescapeTypes::VarBit,
                0,
                11,
            ),
            'the_enchanted_key' => $this->makeObject(
                'The Enchanted Key',
                13717,
                RunescapeTypes::VarBit,
                0,
                2,
                RunescapeQuestTypes::Miniquest,
            ),
            'the_eyes_of_glouphrie' => $this->makeObject(
                'The Eyes of Glouphrie',
                2497,
                RunescapeTypes::VarBit,
                0,
                60,
            ),
            'the_feud' => $this->makeObject(
                'The Feud',
                334,
                RunescapeTypes::VarBit,
                0,
                28,
            ),
            'the_forsaken_tower' => $this->makeObject(
                'The Forsaken Tower',
                7796,
                RunescapeTypes::VarBit,
                0,
                11,
            ),
            'the_fremennik_exiles' => $this->makeObject(
                'The Fremennik Exiles',
                9459,
                RunescapeTypes::VarBit,
                0,
                130,
            ),
            'the_freminnik_isles' => $this->makeObject(
                'The Freminnik Isles',
                3311,
                RunescapeTypes::VarBit,
                0,
                340,
            ),
            'the_frozen_door' => $this->makeObject(
                'The Frozen Door',
                13175,
                RunescapeTypes::VarBit,
                0,
                10,
                RunescapeQuestTypes::Miniquest
            ),
            'the_garden_of_death' => $this->makeObject(
                'The Garden of Death',
                14609,
                RunescapeTypes::VarBit,
                0,
                56,
            ),
            'the_generals_shadow' => $this->makeObject(
                "The General's Shadow",
                3330,
                RunescapeTypes::VarBit,
                0,
                30,
                RunescapeQuestTypes::Miniquest,
            ),
            'the_giant_dwarf' => $this->makeObject(
                'The Giant Dwarf',
                571,
                RunescapeTypes::VarBit,
                0,
                50,
            ),
            'the_golem' => $this->makeObject(
                'The Golem',
                346,
                RunescapeTypes::VarBit,
                0,
                10,
            ),
            'the_hand_in_the_sand' => $this->makeObject(
                'The Hand in the Sand',
                1527,
                RunescapeTypes::VarBit,
                0,
                160,
            ),
            'the_lost_tribe' => $this->makeObject(
                'The Lost Tribe',
                532,
                RunescapeTypes::VarBit,
                0,
                11,
            ),
            'the_queen_of_thieves' => $this->makeObject(
                'The Queen of Thieves',
                6037,
                RunescapeTypes::VarBit,
                0,
                13,
            ),
            'the_slug_menace' => $this->makeObject(
                'The Slug Menace',
                2610,
                RunescapeTypes::VarBit,
                0,
                14,
            ),
            'tower_of_life' => $this->makeObject(
                'Tower of Life',
                3337,
                RunescapeTypes::VarBit,
                0,
                18,
            ),
            'wanted' => $this->makeObject(
                'Wanted',
                1051,
                RunescapeTypes::VarBit,
                0,
                11,
            ),
            'what_lies_below' => $this->makeObject(
                'What Lies Below',
                3523,
                RunescapeTypes::VarBit,
                0,
                150,
            ),
            'x_marks_the_spot' => $this->makeObject(
                'X Marks the Spot',
                8063,
                RunescapeTypes::VarBit,
                0,
                8,
            ),
            'zogre_flesh_eaters' => $this->makeObject(
                'Zogre Flesh Eaters',
                487,
                RunescapeTypes::VarBit,
                0,
                11,
            ),
            'big_chompy_bird_hunting' => $this->makeObject(
                'Big Chompy Bird Hunting',
                293,
                RunescapeTypes::VarPlayer,
                0,
                65,
            ),
            'biohazard' => $this->makeObject(
                'Biohazard',
                68,
                RunescapeTypes::VarPlayer,
                0,
                16,
            ),
            'black_knight_fortress' => $this->makeObject(
                "Black Knights' Fortress",
                130,
                RunescapeTypes::VarPlayer,
                0,
                4,
            ),
            'cabin_fever' => $this->makeObject(
                'Cabin Fever',
                655,
                RunescapeTypes::VarPlayer,
                0,
                140
            ),
            'clock_tower' => $this->makeObject(
                'Clock Tower',
                10,
                RunescapeTypes::VarPlayer,
                0,
                8,
            ),
            'cooks_assistant' => $this->makeObject(
                "Cook's assistant",
                29,
                RunescapeTypes::VarPlayer,
                0,
                2,
            ),
            'death_plateau' => $this->makeObject(
                'Death Plateau',
                314,
                RunescapeTypes::VarPlayer,
                0,
                80,
            ),
            'dorics_quest' => $this->makeObject(
                "Doric's Quest",
                31,
                RunescapeTypes::VarPlayer,
                0,
                100,
            ),
            'dragon_slayer_1' => $this->makeObject(
                'Dragon Slayer I',
                176,
                RunescapeTypes::VarPlayer,
                0,
                10,
            ),
            'druidic_ritual' => $this->makeObject(
                'Druidic Ritual',
                80,
                RunescapeTypes::VarPlayer,
                0,
                4,
            ),
            'dwarf_cannon' => $this->makeObject(
                'Dwarf Cannon',
                0,
                RunescapeTypes::VarPlayer,
                0,
                11,
            ),
            'eadgars_ruse' => $this->makeObject(
                "Eadgar's Ruse",
                335,
                RunescapeTypes::VarPlayer,
                0,
                110,
            ),
            'enter_the_abyss' => $this->makeObject(
                'Enter the Abyss',
                492,
                RunescapeTypes::VarPlayer,
                0,
                4,
                RunescapeQuestTypes::Miniquest,
            ),
            'ernest_the_chicken' => $this->makeObject(
                'Ernest the Chicken',
                148,
                RunescapeTypes::VarPlayer,
                0,
                11,
            ),
            'family_crest' => $this->makeObject(
                'Family Crest',
                148,
                RunescapeTypes::VarPlayer,
                0,
                11,
            ),
            'fight_arena' => $this->makeObject(
                'Fight Arena',
                17,
                RunescapeTypes::VarPlayer,
                0,
                14,
            ),
            'fishing_contest' => $this->makeObject(
                'Fishing Contest',
                11,
                RunescapeTypes::VarPlayer,
                0,
                5,
            ),
            'gertrudes_cat' => $this->makeObject(
                "Gertrude's cat",
                180,
                RunescapeTypes::VarPlayer,
                0,
                6,
            ),
            'haunted_mine' => $this->makeObject(
                'Haunted Mine',
                382,
                RunescapeTypes::VarPlayer,
                0,
                11,
            ),
            'hazeel_cult' => $this->makeObject(
                'Hazeel Cult',
                223,
                RunescapeTypes::VarPlayer,
                0,
                9,
            ),
            'heroes_quest' => $this->makeObject(
                "Heroes' Quest",
                188,
                RunescapeTypes::VarPlayer,
                0,
                15,
            ),
            'holy_grail' => $this->makeObject(
                'Holy Grail',
                5,
                RunescapeTypes::VarPlayer,
                0,
                10,
            ),
            'imp_catcher' => $this->makeObject(
                'Imp Catcher',
                160,
                RunescapeTypes::VarPlayer,
                0,
                2,
            ),
            'in_search_of_the_myreque' => $this->makeObject(
                'In Search of the Myreque',
                387,
                RunescapeTypes::VarPlayer,
                0,
                105,
            ),
            'jungle_potion' => $this->makeObject(
                'Jungle Potion',
                175,
                RunescapeTypes::VarPlayer,
                0,
                12,
            ),
            'legends_quest' => $this->makeObject(
                "Legends' Quest",
                139,
                RunescapeTypes::VarPlayer,
                0,
                75,
            ),
            'lost_city' => $this->makeObject(
                'Lost City',
                147,
                RunescapeTypes::VarPlayer,
                0,
                6,
            ),
            'mage_arena_1' => $this->makeObject(
                'Mage Arena I',
                267,
                RunescapeTypes::VarPlayer,
                0,
                8,
                RunescapeQuestTypes::Miniquest,
            ),
            'merlins_crystal' => $this->makeObject(
                "Merlin's Crystal",
                14,
                RunescapeTypes::VarPlayer,
                0,
                7,
            ),
            'monks_friend' => $this->makeObject(
                "Monk's Friend",
                30,
                RunescapeTypes::VarPlayer,
                0,
                80,
            ),
            'monkey_madness_1' => $this->makeObject(
                'Monkey Madness I',
                365,
                RunescapeTypes::VarPlayer,
                0,
                9,
            ),
            'mournings_end_part_1' => $this->makeObject(
                "Mourning's End Part I",
                517,
                RunescapeTypes::VarPlayer,
                0,
                9,
            ),
            'murder_mystery' => $this->makeObject(
                'Murder Mystery',
                192,
                RunescapeTypes::VarPlayer,
                0,
                2,
            ),
            'nature_spirit' => $this->makeObject(
                'Nature Spirit',
                307,
                RunescapeTypes::VarPlayer,
                0,
                110,
            ),
            'observatory_quest' => $this->makeObject(
                'Observatory Quest',
                112,
                RunescapeTypes::VarPlayer,
                0,
                7,
            ),
            'one_small_favour' => $this->makeObject(
                'One Small Favour',
                416,
                RunescapeTypes::VarPlayer,
                0,
                285,
            ),
            'pirates_treasure' => $this->makeObject(
                "Pirate's Treasure",
                71,
                RunescapeTypes::VarPlayer,
                0,
                4,
            ),
            'plague_city' => $this->makeObject(
                'Plague City',
                165,
                RunescapeTypes::VarPlayer,
                0,
                29,
            ),
            'priest_in_peril' => $this->makeObject(
                'Priest in Peril',
                302,
                RunescapeTypes::VarPlayer,
                0,
                60,
            ),
            'prince_ali_rescue' => $this->makeObject(
                'Prince Ali Rescue',
                273,
                RunescapeTypes::VarPlayer,
                0,
                110,
            ),
            'rag_and_bone_man_1' => $this->makeObject(
                'Rag and Bone Man I',
                714,
                RunescapeTypes::VarPlayer,
                0,
                4,
            ),
            'rag_and_bone_man_2' => $this->makeObject(
                "Rag and Bone Man II",
                714,
                RunescapeTypes::VarPlayer,
                3,
                6,
            ),
            'regicide' => $this->makeObject(
                'Regicide',
                328,
                RunescapeTypes::VarPlayer,
                0,
                15,
            ),
            'romeo_and_juliet' => $this->makeObject(
                'Romeo and Juliet',
                144,
                RunescapeTypes::VarPlayer,
                0,
                100,
            ),
            'roving_elves' => $this->makeObject(
                'Roving Elves',
                402,
                RunescapeTypes::VarPlayer,
                0,
                6,
            ),
            'rum_deal' => $this->makeObject(
                'Rum Deal',
                600,
                RunescapeTypes::VarPlayer,
                0,
                19,
            ),
            'rune_mysteries' => $this->makeObject(
                'Rune Mysteries',
                63,
                RunescapeTypes::VarPlayer,
                0,
                6,
            ),
            'scorpion_catcher' => $this->makeObject(
                'Scorpion Catcher',
                76,
                RunescapeTypes::VarPlayer,
                0,
                6,
            ),
            'sea_slug' => $this->makeObject(
                'Sea Slug',
                159,
                RunescapeTypes::VarPlayer,
                0,
                12,
            ),
            'shades_of_mortton' => $this->makeObject(
                "Shades of Mort'ton",
                339,
                RunescapeTypes::VarPlayer,
                0,
                85,
            ),
            'sheep_herder' => $this->makeObject(
                'Sheep herder',
                60,
                RunescapeTypes::VarPlayer,
                0,
                3,
            ),
            'shilo_village' => $this->makeObject(
                'Shilo Village',
                116,
                RunescapeTypes::VarPlayer,
                0,
                15,
            ),
            'tai_bwo_wannai_trio' => $this->makeObject(
                'Tai Bwo Wannai Trio',
                320,
                RunescapeTypes::VarPlayer,
                2,
                6,
            ),
            'temple_of_ikov' => $this->makeObject(
                'Temple of Ikov',
                26,
                RunescapeTypes::VarPlayer,
                0,
                80,
            ),
            'the_digsite' => $this->makeObject(
                'The Digsite',
                131,
                RunescapeTypes::VarPlayer,
                0,
                9,
            ),
            'the_fremennik_trials' => $this->makeObject(
                'The Fremennik Trials',
                347,
                RunescapeTypes::VarPlayer,
                0,
                10,
            ),
            'the_grand_tree' => $this->makeObject(
                'The Grand Tree',
                150,
                RunescapeTypes::VarPlayer,
                0,
                160,
            ),
            'the_great_brain_robbery' => $this->makeObject(
                'The Great Brain Robbery',
                980,
                RunescapeTypes::VarPlayer,
                0,
                130,
            ),
            'the_knights_sword' => $this->makeObject(
                "The Knight's Sword",
                122,
                RunescapeTypes::VarPlayer,
                0,
                7,
            ),
            'the_restless_ghost' => $this->makeObject(
                'The Restless Ghost',
                107,
                RunescapeTypes::VarPlayer,
                0,
                5,
            ),
            'the_tourist_trap' => $this->makeObject(
                'The Tourist Trap',
                197,
                RunescapeTypes::VarPlayer,
                0,
                30,
            ),
            'throne_of_miscellania' => $this->makeObject(
                'Throne of Miscellania',
                359,
                RunescapeTypes::VarPlayer,
                0,
                100,
            ),
            'tree_gnome_village' => $this->makeObject(
                'Tree Gnome Village',
                111,
                RunescapeTypes::VarPlayer,
                0,
                9,
            ),
            'tribal_totem' => $this->makeObject(
                'Tribal Totem',
                200,
                RunescapeTypes::VarPlayer,
                0,
                5,
            ),
            'troll_romance' => $this->makeObject(
                'Troll Romance',
                385,
                RunescapeTypes::VarPlayer,
                0,
                45,
            ),
            'troll_stronghold' => $this->makeObject(
                'Troll Stronghold',
                317,
                RunescapeTypes::VarPlayer,
                0,
                50,
            ),
            'underground_pass' => $this->makeObject(
                'Underground Pass',
                161,
                RunescapeTypes::VarPlayer,
                0,
                11,
            ),
            'vampyre_slayer' => $this->makeObject(
                'Vampyre Slayer',
                178,
                RunescapeTypes::VarPlayer,
                0,
                3,
            ),
            'watchtower' => $this->makeObject(
                'Watchtower',
                212,
                RunescapeTypes::VarPlayer,
                0,
                13,
            ),
            'waterfall_quest' => $this->makeObject(
                'Waterfall quest',
                65,
                RunescapeTypes::VarPlayer,
                0,
                10,
            ),
            'witchs_house' => $this->makeObject(
                "Witch's house",
                226,
                RunescapeTypes::VarPlayer,
                0,
                7,
            ),
            'witchs_potion' => $this->makeObject(
                "Witch's potion",
                67,
                RunescapeTypes::VarPlayer,
                0,
                3,
            ),
        ];

        uasort($data, fn ($a, $b) => strcmp($a['text'], $b['text']));

        return $data;
    }

    private function makeObject(
        string $text,
        int $index,
        RunescapeTypes $type,
        int $startValue,
        int $endValue,
        RunescapeQuestTypes $questType = RunescapeQuestTypes::Quest,
    ): array {
        return [
            'index' => $index,
            'type' => $type,
            'questType' => $questType,
            'startValue' => $startValue,
            'endValue' => $endValue,
            'text' => $text
        ];
    }
}
